export { default as SignInView } from './SignInView.vue'
export { default as SignUpView } from './SignUpView.vue'
export { default as VerifyEmailView } from './VerifyEmailView.vue'
export { default as VerifyEmailCallbackView } from './VerifyEmailCallbackView.vue'
export { default as ForgotPasswordView } from './ForgotPasswordView.vue'
export { default as ResetPasswordView } from './ResetPasswordView.vue'
